#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef ECPAYPAYMENTGATEWAYKIT_SWIFT_H
#define ECPAYPAYMENTGATEWAYKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import Security;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ECPayPaymentGatewayKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


enum CallbackStateStatusType : NSInteger;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit13CallbackState")
@interface CallbackState : NSObject
@property (nonatomic) enum CallbackStateStatusType callbackStateStatus;
@property (nonatomic, copy) NSString * _Nonnull callbackStateMessage;
- (NSString * _Nonnull)statusToString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CallbackStateStatusType, open) {
  CallbackStateStatusTypeFail = 0,
  CallbackStateStatusTypeSuccess = 1,
  CallbackStateStatusTypeCancel = 2,
  CallbackStateStatusTypeUnknown = 999,
};

enum CreatePaymentCallbackState_PaymentType : NSInteger;
@class CreatePaymentCallbackState_OrderInfoResponseModel;
@class CreatePaymentCallbackState_CardInfoResponseModel;
@class CreatePaymentCallbackState_ATMInfoResponseModel;
@class CreatePaymentCallbackState_CVSInfoResponseModel;
@class CreatePaymentCallbackState_BarcodeInfoResponseModel;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit26CreatePaymentCallbackState")
@interface CreatePaymentCallbackState : CallbackState
@property (nonatomic) NSInteger RtnCode;
@property (nonatomic, copy) NSString * _Nonnull RtnMsg;
@property (nonatomic) enum CreatePaymentCallbackState_PaymentType PaymentType;
@property (nonatomic, copy) NSString * _Nullable PlatformID;
@property (nonatomic) NSInteger MerchantID;
@property (nonatomic) NSInteger MerchantMemberID;
@property (nonatomic, strong) CreatePaymentCallbackState_OrderInfoResponseModel * _Nullable OrderInfo;
@property (nonatomic, strong) CreatePaymentCallbackState_CardInfoResponseModel * _Nullable CardInfo;
@property (nonatomic, strong) CreatePaymentCallbackState_ATMInfoResponseModel * _Nullable ATMInfo;
@property (nonatomic, strong) CreatePaymentCallbackState_CVSInfoResponseModel * _Nullable CVSInfo;
@property (nonatomic, strong) CreatePaymentCallbackState_BarcodeInfoResponseModel * _Nullable BarcodeInfo;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit47CreatePaymentCallbackState_ATMInfoResponseModel")
@interface CreatePaymentCallbackState_ATMInfoResponseModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit51CreatePaymentCallbackState_BarcodeInfoResponseModel")
@interface CreatePaymentCallbackState_BarcodeInfoResponseModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit47CreatePaymentCallbackState_CVSInfoResponseModel")
@interface CreatePaymentCallbackState_CVSInfoResponseModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit48CreatePaymentCallbackState_CardInfoResponseModel")
@interface CreatePaymentCallbackState_CardInfoResponseModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit49CreatePaymentCallbackState_OrderInfoResponseModel")
@interface CreatePaymentCallbackState_OrderInfoResponseModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

typedef SWIFT_ENUM(NSInteger, CreatePaymentCallbackState_PaymentType, open) {
  CreatePaymentCallbackState_PaymentTypeCreditCard = 0,
  CreatePaymentCallbackState_PaymentTypeCreditInstallment = 1,
  CreatePaymentCallbackState_PaymentTypeATM = 2,
  CreatePaymentCallbackState_PaymentTypeCVS = 3,
  CreatePaymentCallbackState_PaymentTypeBarcode = 4,
  CreatePaymentCallbackState_PaymentTypeOPay = 5,
  CreatePaymentCallbackState_PaymentTypeApplePay = 6,
  CreatePaymentCallbackState_PaymentTypeGooglePay = 7,
  CreatePaymentCallbackState_PaymentTypeSamsungPay = 8,
  CreatePaymentCallbackState_PaymentTypePeriodicFixedAmount = 9,
  CreatePaymentCallbackState_PaymentTypeNationalTravelCard = 10,
  CreatePaymentCallbackState_PaymentTypeUnknown = 999,
};


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit23CustomErrorMessageParam")
@interface CustomErrorMessageParam : NSObject
@property (nonatomic, copy) NSString * _Nonnull customErrorAlertTitle;
@property (nonatomic, copy) NSString * _Nonnull customErrorAlertMessage;
@property (nonatomic) BOOL completionAfterCustomErrorAlertMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum EnvironmentType : NSInteger;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit26ECPayPaymentGatewayManager")
@interface ECPayPaymentGatewayManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (ECPayPaymentGatewayManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)initialize;
- (void)initializeWithEnv:(enum EnvironmentType)env;
- (NSString * _Nonnull)sdkEnvironmentString SWIFT_WARN_UNUSED_RESULT;
- (void)createPaymentWithToken:(NSString * _Nonnull)token merchantID:(NSString * _Nonnull)merchantID useResultPage:(NSInteger)useResultPage appStoreName:(NSString * _Nonnull)appStoreName language:(NSString * _Nonnull)language callback:(void (^ _Nonnull)(CallbackState * _Nonnull))callback;
- (void)testToGetTestingTradeTokenWithPaymentUIType:(NSInteger)paymentUIType is3D:(BOOL)is3D merchantID:(NSString * _Nonnull)merchantID aesKey:(NSString * _Nonnull)aesKey aesIV:(NSString * _Nonnull)aesIV callback:(void (^ _Nonnull)(CallbackState * _Nonnull))callback;
- (void)testToGetTestingUserTokenWithIs3D:(BOOL)is3D merchantID:(NSString * _Nonnull)merchantID aesKey:(NSString * _Nonnull)aesKey aesIV:(NSString * _Nonnull)aesIV callback:(void (^ _Nonnull)(CallbackState * _Nonnull))callback;
- (void)testToLaunchApiTestUIWithTokenType:(NSInteger)tokenType tokenTypeString:(NSString * _Nonnull)tokenTypeString token:(NSString * _Nonnull)token callback:(void (^ _Nonnull)(CallbackState * _Nonnull))callback;
- (void)testInit;
- (void)testAlamofire;
- (void)testSwiftyXMLParser;
- (void)testIQKeyboard;
- (void)testKeyChain;
- (void)testAPI;
@end

typedef SWIFT_ENUM(NSInteger, EnvironmentType, open) {
  EnvironmentTypeBeta = 0,
  EnvironmentTypeStage = 1,
  EnvironmentTypeProd = 2,
};


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit15ExitConfirmParm")
@interface ExitConfirmParm : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, copy) NSString * _Nonnull action1;
@property (nonatomic, copy) NSString * _Nonnull action2;
@property (nonatomic) BOOL inherit;
- (nonnull instancetype)init:(NSString * _Nonnull)title message:(NSString * _Nonnull)message;
- (nonnull instancetype)init:(NSString * _Nonnull)title message:(NSString * _Nonnull)message action1:(NSString * _Nonnull)action1 action2:(NSString * _Nonnull)action2;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit17WebViewController")
@interface WebViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (void)load:(NSURLRequest * _Nonnull)urlRequest;
- (void)setNavigationTitle:(NSString * _Nonnull)title;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WKWebView;
@class WKNavigation;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit19GwWebviewController")
@interface GwWebviewController : WebViewController
@property (nonatomic, copy) void (^ _Nullable completion)(void);
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit28LaunchApiTestUICallbackState")
@interface LaunchApiTestUICallbackState : CallbackState
@property (nonatomic) NSInteger RtnCode;
@property (nonatomic, copy) NSString * _Nonnull RtnMsg;
@property (nonatomic, strong) CreatePaymentCallbackState * _Nullable CreatePaymentCallbackResult;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit25TestingTokenCallbackState")
@interface TestingTokenCallbackState : CallbackState
@property (nonatomic) NSInteger RtnCode;
@property (nonatomic, copy) NSString * _Nonnull RtnMsg;
@property (nonatomic, copy) NSString * _Nonnull Token;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





















@class WKUserContentController;
@class WKScriptMessage;

@interface WebViewController (SWIFT_EXTENSION(ECPayPaymentGatewayKit)) <WKScriptMessageHandler>
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end

@class WKWebViewConfiguration;
@class WKNavigationAction;
@class WKWindowFeatures;
@class WKFrameInfo;

@interface WebViewController (SWIFT_EXTENSION(ECPayPaymentGatewayKit)) <WKUIDelegate>
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
@end

@class WKNavigationResponse;

@interface WebViewController (SWIFT_EXTENSION(ECPayPaymentGatewayKit)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationResponse:(WKNavigationResponse * _Nonnull)navigationResponse decisionHandler:(void (^ _Nonnull)(WKNavigationResponsePolicy))decisionHandler;
@end

@class UIColor;
@class UINavigationController;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit14WebViewManager")
@interface WebViewManager : NSObject
+ (void)showWeb:(NSString * _Nonnull)url title:(NSString * _Nullable)title completion:(void (^ _Nullable)(void))completion;
+ (void)showWeb:(NSString * _Nonnull)url from:(UIViewController * _Nullable)from title:(NSString * _Nullable)title completion:(void (^ _Nullable)(void))completion;
+ (void)showWeb:(NSString * _Nonnull)url from:(UIViewController * _Nullable)from title:(NSString * _Nullable)title navColor:(UIColor * _Nullable)navColor completion:(void (^ _Nullable)(void))completion;
+ (UIViewController * _Nonnull)getWebViewControllerUseIntermediate:(NSString * _Nonnull)url title:(NSString * _Nullable)title completion:(void (^ _Nullable)(void))completion SWIFT_WARN_UNUSED_RESULT;
+ (UINavigationController * _Nonnull)getWebNavUseIntermediate:(NSString * _Nonnull)url parameters:(NSDictionary<NSString *, id> * _Nonnull)parameters title:(NSString * _Nullable)title customErrorMessageParam:(CustomErrorMessageParam * _Nullable)customErrorMessageParam completion:(void (^ _Nullable)(void))completion SWIFT_WARN_UNUSED_RESULT;
+ (UINavigationController * _Nonnull)getWebNavUseIntermediate:(NSString * _Nonnull)url parameters:(NSDictionary<NSString *, id> * _Nonnull)parameters title:(NSString * _Nullable)title customErrorMessageParam:(CustomErrorMessageParam * _Nullable)customErrorMessageParam exitConfirmParm:(ExitConfirmParm * _Nullable)exitConfirmParm completion:(void (^ _Nullable)(void))completion SWIFT_WARN_UNUSED_RESULT;
+ (void)showWebUseIntermediate:(NSString * _Nonnull)url title:(NSString * _Nullable)title completion:(void (^ _Nullable)(void))completion;
+ (void)showWebUseIntermediate:(NSString * _Nonnull)url from:(UIViewController * _Nullable)from title:(NSString * _Nullable)title completion:(void (^ _Nullable)(void))completion;
/// 載入原生瀏覽器
/// \param url 目標URL
///
+ (void)showNativeWeb:(NSString * _Nonnull)url completion:(void (^ _Nullable)(void))completion;
/// 載入原生瀏覽器，使用中轉頁
/// \param url 目標URL
///
+ (void)showNativeWebUseIntermediate:(NSString * _Nonnull)url completion:(void (^ _Nullable)(void))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit23XMLConfigurationManager")
@interface XMLConfigurationManager : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@class PublicKey;
@class EncryptedMessage;
@class PrivateKey;
enum DigestType : NSInteger;
@class Signature;
@class VerificationResult;

SWIFT_CLASS_NAMED("_objc_ClearMessage")
@interface ClearMessage : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull base64String;
@property (nonatomic, readonly, copy) NSData * _Nonnull data;
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithString:(NSString * _Nonnull)string using:(NSUInteger)rawEncoding error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)stringWithEncoding:(NSUInteger)rawEncoding error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (EncryptedMessage * _Nullable)encryptedWith:(PublicKey * _Nonnull)key padding:(SecPadding)padding error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (Signature * _Nullable)signedWith:(PrivateKey * _Nonnull)key digestType:(enum DigestType)digestType error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (VerificationResult * _Nullable)verifyWith:(PublicKey * _Nonnull)key signature:(Signature * _Nonnull)signature digestType:(enum DigestType)digestType error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("_objc_EncryptedMessage")
@interface EncryptedMessage : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull base64String;
@property (nonatomic, readonly, copy) NSData * _Nonnull data;
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (ClearMessage * _Nullable)decryptedWith:(PrivateKey * _Nonnull)key padding:(SecPadding)padding error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("_objc_PrivateKey")
@interface PrivateKey : NSObject
@property (nonatomic, readonly) SecKeyRef _Nonnull reference;
@property (nonatomic, readonly, copy) NSData * _Nullable originalData;
- (NSString * _Nullable)pemStringAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)dataAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)base64StringAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithData:(NSData * _Nonnull)data error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithReference:(SecKeyRef _Nonnull)reference error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithPemEncoded:(NSString * _Nonnull)pemString error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithPemNamed:(NSString * _Nonnull)pemName in:(NSBundle * _Nonnull)bundle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithDerNamed:(NSString * _Nonnull)derName in:(NSBundle * _Nonnull)bundle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("_objc_PublicKey")
@interface PublicKey : NSObject
@property (nonatomic, readonly) SecKeyRef _Nonnull reference;
@property (nonatomic, readonly, copy) NSData * _Nullable originalData;
- (NSString * _Nullable)pemStringAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)dataAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)base64StringAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithData:(NSData * _Nonnull)data error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithReference:(SecKeyRef _Nonnull)reference error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithPemEncoded:(NSString * _Nonnull)pemString error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithPemNamed:(NSString * _Nonnull)pemName in:(NSBundle * _Nonnull)bundle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithDerNamed:(NSString * _Nonnull)derName in:(NSBundle * _Nonnull)bundle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<PublicKey *> * _Nonnull)publicKeysWithPemEncoded:(NSString * _Nonnull)pemString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("_objc_Signature")
@interface Signature : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull base64String;
@property (nonatomic, readonly, copy) NSData * _Nonnull data;
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DigestType, open) {
  DigestTypeSha1 = 0,
  DigestTypeSha224 = 1,
  DigestTypeSha256 = 2,
  DigestTypeSha384 = 3,
  DigestTypeSha512 = 4,
};


SWIFT_CLASS_NAMED("_objc_VerificationResult")
@interface VerificationResult : NSObject
@property (nonatomic, readonly) BOOL isSuccessful;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef ECPAYPAYMENTGATEWAYKIT_SWIFT_H
#define ECPAYPAYMENTGATEWAYKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import Security;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ECPayPaymentGatewayKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


enum CallbackStateStatusType : NSInteger;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit13CallbackState")
@interface CallbackState : NSObject
@property (nonatomic) enum CallbackStateStatusType callbackStateStatus;
@property (nonatomic, copy) NSString * _Nonnull callbackStateMessage;
- (NSString * _Nonnull)statusToString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CallbackStateStatusType, open) {
  CallbackStateStatusTypeFail = 0,
  CallbackStateStatusTypeSuccess = 1,
  CallbackStateStatusTypeCancel = 2,
  CallbackStateStatusTypeUnknown = 999,
};

enum CreatePaymentCallbackState_PaymentType : NSInteger;
@class CreatePaymentCallbackState_OrderInfoResponseModel;
@class CreatePaymentCallbackState_CardInfoResponseModel;
@class CreatePaymentCallbackState_ATMInfoResponseModel;
@class CreatePaymentCallbackState_CVSInfoResponseModel;
@class CreatePaymentCallbackState_BarcodeInfoResponseModel;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit26CreatePaymentCallbackState")
@interface CreatePaymentCallbackState : CallbackState
@property (nonatomic) NSInteger RtnCode;
@property (nonatomic, copy) NSString * _Nonnull RtnMsg;
@property (nonatomic) enum CreatePaymentCallbackState_PaymentType PaymentType;
@property (nonatomic, copy) NSString * _Nullable PlatformID;
@property (nonatomic) NSInteger MerchantID;
@property (nonatomic) NSInteger MerchantMemberID;
@property (nonatomic, strong) CreatePaymentCallbackState_OrderInfoResponseModel * _Nullable OrderInfo;
@property (nonatomic, strong) CreatePaymentCallbackState_CardInfoResponseModel * _Nullable CardInfo;
@property (nonatomic, strong) CreatePaymentCallbackState_ATMInfoResponseModel * _Nullable ATMInfo;
@property (nonatomic, strong) CreatePaymentCallbackState_CVSInfoResponseModel * _Nullable CVSInfo;
@property (nonatomic, strong) CreatePaymentCallbackState_BarcodeInfoResponseModel * _Nullable BarcodeInfo;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit47CreatePaymentCallbackState_ATMInfoResponseModel")
@interface CreatePaymentCallbackState_ATMInfoResponseModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit51CreatePaymentCallbackState_BarcodeInfoResponseModel")
@interface CreatePaymentCallbackState_BarcodeInfoResponseModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit47CreatePaymentCallbackState_CVSInfoResponseModel")
@interface CreatePaymentCallbackState_CVSInfoResponseModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit48CreatePaymentCallbackState_CardInfoResponseModel")
@interface CreatePaymentCallbackState_CardInfoResponseModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit49CreatePaymentCallbackState_OrderInfoResponseModel")
@interface CreatePaymentCallbackState_OrderInfoResponseModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

typedef SWIFT_ENUM(NSInteger, CreatePaymentCallbackState_PaymentType, open) {
  CreatePaymentCallbackState_PaymentTypeCreditCard = 0,
  CreatePaymentCallbackState_PaymentTypeCreditInstallment = 1,
  CreatePaymentCallbackState_PaymentTypeATM = 2,
  CreatePaymentCallbackState_PaymentTypeCVS = 3,
  CreatePaymentCallbackState_PaymentTypeBarcode = 4,
  CreatePaymentCallbackState_PaymentTypeOPay = 5,
  CreatePaymentCallbackState_PaymentTypeApplePay = 6,
  CreatePaymentCallbackState_PaymentTypeGooglePay = 7,
  CreatePaymentCallbackState_PaymentTypeSamsungPay = 8,
  CreatePaymentCallbackState_PaymentTypePeriodicFixedAmount = 9,
  CreatePaymentCallbackState_PaymentTypeNationalTravelCard = 10,
  CreatePaymentCallbackState_PaymentTypeUnknown = 999,
};


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit23CustomErrorMessageParam")
@interface CustomErrorMessageParam : NSObject
@property (nonatomic, copy) NSString * _Nonnull customErrorAlertTitle;
@property (nonatomic, copy) NSString * _Nonnull customErrorAlertMessage;
@property (nonatomic) BOOL completionAfterCustomErrorAlertMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum EnvironmentType : NSInteger;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit26ECPayPaymentGatewayManager")
@interface ECPayPaymentGatewayManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (ECPayPaymentGatewayManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)initialize;
- (void)initializeWithEnv:(enum EnvironmentType)env;
- (NSString * _Nonnull)sdkEnvironmentString SWIFT_WARN_UNUSED_RESULT;
- (void)createPaymentWithToken:(NSString * _Nonnull)token merchantID:(NSString * _Nonnull)merchantID useResultPage:(NSInteger)useResultPage appStoreName:(NSString * _Nonnull)appStoreName language:(NSString * _Nonnull)language callback:(void (^ _Nonnull)(CallbackState * _Nonnull))callback;
- (void)testToGetTestingTradeTokenWithPaymentUIType:(NSInteger)paymentUIType is3D:(BOOL)is3D merchantID:(NSString * _Nonnull)merchantID aesKey:(NSString * _Nonnull)aesKey aesIV:(NSString * _Nonnull)aesIV callback:(void (^ _Nonnull)(CallbackState * _Nonnull))callback;
- (void)testToGetTestingUserTokenWithIs3D:(BOOL)is3D merchantID:(NSString * _Nonnull)merchantID aesKey:(NSString * _Nonnull)aesKey aesIV:(NSString * _Nonnull)aesIV callback:(void (^ _Nonnull)(CallbackState * _Nonnull))callback;
- (void)testToLaunchApiTestUIWithTokenType:(NSInteger)tokenType tokenTypeString:(NSString * _Nonnull)tokenTypeString token:(NSString * _Nonnull)token callback:(void (^ _Nonnull)(CallbackState * _Nonnull))callback;
- (void)testInit;
- (void)testAlamofire;
- (void)testSwiftyXMLParser;
- (void)testIQKeyboard;
- (void)testKeyChain;
- (void)testAPI;
@end

typedef SWIFT_ENUM(NSInteger, EnvironmentType, open) {
  EnvironmentTypeBeta = 0,
  EnvironmentTypeStage = 1,
  EnvironmentTypeProd = 2,
};


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit15ExitConfirmParm")
@interface ExitConfirmParm : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, copy) NSString * _Nonnull action1;
@property (nonatomic, copy) NSString * _Nonnull action2;
@property (nonatomic) BOOL inherit;
- (nonnull instancetype)init:(NSString * _Nonnull)title message:(NSString * _Nonnull)message;
- (nonnull instancetype)init:(NSString * _Nonnull)title message:(NSString * _Nonnull)message action1:(NSString * _Nonnull)action1 action2:(NSString * _Nonnull)action2;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit17WebViewController")
@interface WebViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (void)load:(NSURLRequest * _Nonnull)urlRequest;
- (void)setNavigationTitle:(NSString * _Nonnull)title;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WKWebView;
@class WKNavigation;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit19GwWebviewController")
@interface GwWebviewController : WebViewController
@property (nonatomic, copy) void (^ _Nullable completion)(void);
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit28LaunchApiTestUICallbackState")
@interface LaunchApiTestUICallbackState : CallbackState
@property (nonatomic) NSInteger RtnCode;
@property (nonatomic, copy) NSString * _Nonnull RtnMsg;
@property (nonatomic, strong) CreatePaymentCallbackState * _Nullable CreatePaymentCallbackResult;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit25TestingTokenCallbackState")
@interface TestingTokenCallbackState : CallbackState
@property (nonatomic) NSInteger RtnCode;
@property (nonatomic, copy) NSString * _Nonnull RtnMsg;
@property (nonatomic, copy) NSString * _Nonnull Token;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





















@class WKUserContentController;
@class WKScriptMessage;

@interface WebViewController (SWIFT_EXTENSION(ECPayPaymentGatewayKit)) <WKScriptMessageHandler>
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end

@class WKWebViewConfiguration;
@class WKNavigationAction;
@class WKWindowFeatures;
@class WKFrameInfo;

@interface WebViewController (SWIFT_EXTENSION(ECPayPaymentGatewayKit)) <WKUIDelegate>
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
@end

@class WKNavigationResponse;

@interface WebViewController (SWIFT_EXTENSION(ECPayPaymentGatewayKit)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationResponse:(WKNavigationResponse * _Nonnull)navigationResponse decisionHandler:(void (^ _Nonnull)(WKNavigationResponsePolicy))decisionHandler;
@end

@class UIColor;
@class UINavigationController;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit14WebViewManager")
@interface WebViewManager : NSObject
+ (void)showWeb:(NSString * _Nonnull)url title:(NSString * _Nullable)title completion:(void (^ _Nullable)(void))completion;
+ (void)showWeb:(NSString * _Nonnull)url from:(UIViewController * _Nullable)from title:(NSString * _Nullable)title completion:(void (^ _Nullable)(void))completion;
+ (void)showWeb:(NSString * _Nonnull)url from:(UIViewController * _Nullable)from title:(NSString * _Nullable)title navColor:(UIColor * _Nullable)navColor completion:(void (^ _Nullable)(void))completion;
+ (UIViewController * _Nonnull)getWebViewControllerUseIntermediate:(NSString * _Nonnull)url title:(NSString * _Nullable)title completion:(void (^ _Nullable)(void))completion SWIFT_WARN_UNUSED_RESULT;
+ (UINavigationController * _Nonnull)getWebNavUseIntermediate:(NSString * _Nonnull)url parameters:(NSDictionary<NSString *, id> * _Nonnull)parameters title:(NSString * _Nullable)title customErrorMessageParam:(CustomErrorMessageParam * _Nullable)customErrorMessageParam completion:(void (^ _Nullable)(void))completion SWIFT_WARN_UNUSED_RESULT;
+ (UINavigationController * _Nonnull)getWebNavUseIntermediate:(NSString * _Nonnull)url parameters:(NSDictionary<NSString *, id> * _Nonnull)parameters title:(NSString * _Nullable)title customErrorMessageParam:(CustomErrorMessageParam * _Nullable)customErrorMessageParam exitConfirmParm:(ExitConfirmParm * _Nullable)exitConfirmParm completion:(void (^ _Nullable)(void))completion SWIFT_WARN_UNUSED_RESULT;
+ (void)showWebUseIntermediate:(NSString * _Nonnull)url title:(NSString * _Nullable)title completion:(void (^ _Nullable)(void))completion;
+ (void)showWebUseIntermediate:(NSString * _Nonnull)url from:(UIViewController * _Nullable)from title:(NSString * _Nullable)title completion:(void (^ _Nullable)(void))completion;
/// 載入原生瀏覽器
/// \param url 目標URL
///
+ (void)showNativeWeb:(NSString * _Nonnull)url completion:(void (^ _Nullable)(void))completion;
/// 載入原生瀏覽器，使用中轉頁
/// \param url 目標URL
///
+ (void)showNativeWebUseIntermediate:(NSString * _Nonnull)url completion:(void (^ _Nullable)(void))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit23XMLConfigurationManager")
@interface XMLConfigurationManager : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@class PublicKey;
@class EncryptedMessage;
@class PrivateKey;
enum DigestType : NSInteger;
@class Signature;
@class VerificationResult;

SWIFT_CLASS_NAMED("_objc_ClearMessage")
@interface ClearMessage : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull base64String;
@property (nonatomic, readonly, copy) NSData * _Nonnull data;
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithString:(NSString * _Nonnull)string using:(NSUInteger)rawEncoding error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)stringWithEncoding:(NSUInteger)rawEncoding error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (EncryptedMessage * _Nullable)encryptedWith:(PublicKey * _Nonnull)key padding:(SecPadding)padding error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (Signature * _Nullable)signedWith:(PrivateKey * _Nonnull)key digestType:(enum DigestType)digestType error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (VerificationResult * _Nullable)verifyWith:(PublicKey * _Nonnull)key signature:(Signature * _Nonnull)signature digestType:(enum DigestType)digestType error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("_objc_EncryptedMessage")
@interface EncryptedMessage : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull base64String;
@property (nonatomic, readonly, copy) NSData * _Nonnull data;
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (ClearMessage * _Nullable)decryptedWith:(PrivateKey * _Nonnull)key padding:(SecPadding)padding error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("_objc_PrivateKey")
@interface PrivateKey : NSObject
@property (nonatomic, readonly) SecKeyRef _Nonnull reference;
@property (nonatomic, readonly, copy) NSData * _Nullable originalData;
- (NSString * _Nullable)pemStringAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)dataAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)base64StringAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithData:(NSData * _Nonnull)data error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithReference:(SecKeyRef _Nonnull)reference error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithPemEncoded:(NSString * _Nonnull)pemString error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithPemNamed:(NSString * _Nonnull)pemName in:(NSBundle * _Nonnull)bundle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithDerNamed:(NSString * _Nonnull)derName in:(NSBundle * _Nonnull)bundle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("_objc_PublicKey")
@interface PublicKey : NSObject
@property (nonatomic, readonly) SecKeyRef _Nonnull reference;
@property (nonatomic, readonly, copy) NSData * _Nullable originalData;
- (NSString * _Nullable)pemStringAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)dataAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)base64StringAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithData:(NSData * _Nonnull)data error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithReference:(SecKeyRef _Nonnull)reference error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithPemEncoded:(NSString * _Nonnull)pemString error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithPemNamed:(NSString * _Nonnull)pemName in:(NSBundle * _Nonnull)bundle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithDerNamed:(NSString * _Nonnull)derName in:(NSBundle * _Nonnull)bundle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<PublicKey *> * _Nonnull)publicKeysWithPemEncoded:(NSString * _Nonnull)pemString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("_objc_Signature")
@interface Signature : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull base64String;
@property (nonatomic, readonly, copy) NSData * _Nonnull data;
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DigestType, open) {
  DigestTypeSha1 = 0,
  DigestTypeSha224 = 1,
  DigestTypeSha256 = 2,
  DigestTypeSha384 = 3,
  DigestTypeSha512 = 4,
};


SWIFT_CLASS_NAMED("_objc_VerificationResult")
@interface VerificationResult : NSObject
@property (nonatomic, readonly) BOOL isSuccessful;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__i386__) && __i386__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef ECPAYPAYMENTGATEWAYKIT_SWIFT_H
#define ECPAYPAYMENTGATEWAYKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import Security;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ECPayPaymentGatewayKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


enum CallbackStateStatusType : NSInteger;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit13CallbackState")
@interface CallbackState : NSObject
@property (nonatomic) enum CallbackStateStatusType callbackStateStatus;
@property (nonatomic, copy) NSString * _Nonnull callbackStateMessage;
- (NSString * _Nonnull)statusToString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CallbackStateStatusType, open) {
  CallbackStateStatusTypeFail = 0,
  CallbackStateStatusTypeSuccess = 1,
  CallbackStateStatusTypeCancel = 2,
  CallbackStateStatusTypeUnknown = 999,
};

enum CreatePaymentCallbackState_PaymentType : NSInteger;
@class CreatePaymentCallbackState_OrderInfoResponseModel;
@class CreatePaymentCallbackState_CardInfoResponseModel;
@class CreatePaymentCallbackState_ATMInfoResponseModel;
@class CreatePaymentCallbackState_CVSInfoResponseModel;
@class CreatePaymentCallbackState_BarcodeInfoResponseModel;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit26CreatePaymentCallbackState")
@interface CreatePaymentCallbackState : CallbackState
@property (nonatomic) NSInteger RtnCode;
@property (nonatomic, copy) NSString * _Nonnull RtnMsg;
@property (nonatomic) enum CreatePaymentCallbackState_PaymentType PaymentType;
@property (nonatomic, copy) NSString * _Nullable PlatformID;
@property (nonatomic) NSInteger MerchantID;
@property (nonatomic) NSInteger MerchantMemberID;
@property (nonatomic, strong) CreatePaymentCallbackState_OrderInfoResponseModel * _Nullable OrderInfo;
@property (nonatomic, strong) CreatePaymentCallbackState_CardInfoResponseModel * _Nullable CardInfo;
@property (nonatomic, strong) CreatePaymentCallbackState_ATMInfoResponseModel * _Nullable ATMInfo;
@property (nonatomic, strong) CreatePaymentCallbackState_CVSInfoResponseModel * _Nullable CVSInfo;
@property (nonatomic, strong) CreatePaymentCallbackState_BarcodeInfoResponseModel * _Nullable BarcodeInfo;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit47CreatePaymentCallbackState_ATMInfoResponseModel")
@interface CreatePaymentCallbackState_ATMInfoResponseModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit51CreatePaymentCallbackState_BarcodeInfoResponseModel")
@interface CreatePaymentCallbackState_BarcodeInfoResponseModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit47CreatePaymentCallbackState_CVSInfoResponseModel")
@interface CreatePaymentCallbackState_CVSInfoResponseModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit48CreatePaymentCallbackState_CardInfoResponseModel")
@interface CreatePaymentCallbackState_CardInfoResponseModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit49CreatePaymentCallbackState_OrderInfoResponseModel")
@interface CreatePaymentCallbackState_OrderInfoResponseModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

typedef SWIFT_ENUM(NSInteger, CreatePaymentCallbackState_PaymentType, open) {
  CreatePaymentCallbackState_PaymentTypeCreditCard = 0,
  CreatePaymentCallbackState_PaymentTypeCreditInstallment = 1,
  CreatePaymentCallbackState_PaymentTypeATM = 2,
  CreatePaymentCallbackState_PaymentTypeCVS = 3,
  CreatePaymentCallbackState_PaymentTypeBarcode = 4,
  CreatePaymentCallbackState_PaymentTypeOPay = 5,
  CreatePaymentCallbackState_PaymentTypeApplePay = 6,
  CreatePaymentCallbackState_PaymentTypeGooglePay = 7,
  CreatePaymentCallbackState_PaymentTypeSamsungPay = 8,
  CreatePaymentCallbackState_PaymentTypePeriodicFixedAmount = 9,
  CreatePaymentCallbackState_PaymentTypeNationalTravelCard = 10,
  CreatePaymentCallbackState_PaymentTypeUnknown = 999,
};


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit23CustomErrorMessageParam")
@interface CustomErrorMessageParam : NSObject
@property (nonatomic, copy) NSString * _Nonnull customErrorAlertTitle;
@property (nonatomic, copy) NSString * _Nonnull customErrorAlertMessage;
@property (nonatomic) BOOL completionAfterCustomErrorAlertMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum EnvironmentType : NSInteger;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit26ECPayPaymentGatewayManager")
@interface ECPayPaymentGatewayManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (ECPayPaymentGatewayManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)initialize;
- (void)initializeWithEnv:(enum EnvironmentType)env;
- (NSString * _Nonnull)sdkEnvironmentString SWIFT_WARN_UNUSED_RESULT;
- (void)createPaymentWithToken:(NSString * _Nonnull)token merchantID:(NSString * _Nonnull)merchantID useResultPage:(NSInteger)useResultPage appStoreName:(NSString * _Nonnull)appStoreName language:(NSString * _Nonnull)language callback:(void (^ _Nonnull)(CallbackState * _Nonnull))callback;
- (void)testToGetTestingTradeTokenWithPaymentUIType:(NSInteger)paymentUIType is3D:(BOOL)is3D merchantID:(NSString * _Nonnull)merchantID aesKey:(NSString * _Nonnull)aesKey aesIV:(NSString * _Nonnull)aesIV callback:(void (^ _Nonnull)(CallbackState * _Nonnull))callback;
- (void)testToGetTestingUserTokenWithIs3D:(BOOL)is3D merchantID:(NSString * _Nonnull)merchantID aesKey:(NSString * _Nonnull)aesKey aesIV:(NSString * _Nonnull)aesIV callback:(void (^ _Nonnull)(CallbackState * _Nonnull))callback;
- (void)testToLaunchApiTestUIWithTokenType:(NSInteger)tokenType tokenTypeString:(NSString * _Nonnull)tokenTypeString token:(NSString * _Nonnull)token callback:(void (^ _Nonnull)(CallbackState * _Nonnull))callback;
- (void)testInit;
- (void)testAlamofire;
- (void)testSwiftyXMLParser;
- (void)testIQKeyboard;
- (void)testKeyChain;
- (void)testAPI;
@end

typedef SWIFT_ENUM(NSInteger, EnvironmentType, open) {
  EnvironmentTypeBeta = 0,
  EnvironmentTypeStage = 1,
  EnvironmentTypeProd = 2,
};


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit15ExitConfirmParm")
@interface ExitConfirmParm : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, copy) NSString * _Nonnull action1;
@property (nonatomic, copy) NSString * _Nonnull action2;
@property (nonatomic) BOOL inherit;
- (nonnull instancetype)init:(NSString * _Nonnull)title message:(NSString * _Nonnull)message;
- (nonnull instancetype)init:(NSString * _Nonnull)title message:(NSString * _Nonnull)message action1:(NSString * _Nonnull)action1 action2:(NSString * _Nonnull)action2;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit17WebViewController")
@interface WebViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (void)load:(NSURLRequest * _Nonnull)urlRequest;
- (void)setNavigationTitle:(NSString * _Nonnull)title;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WKWebView;
@class WKNavigation;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit19GwWebviewController")
@interface GwWebviewController : WebViewController
@property (nonatomic, copy) void (^ _Nullable completion)(void);
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit28LaunchApiTestUICallbackState")
@interface LaunchApiTestUICallbackState : CallbackState
@property (nonatomic) NSInteger RtnCode;
@property (nonatomic, copy) NSString * _Nonnull RtnMsg;
@property (nonatomic, strong) CreatePaymentCallbackState * _Nullable CreatePaymentCallbackResult;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit25TestingTokenCallbackState")
@interface TestingTokenCallbackState : CallbackState
@property (nonatomic) NSInteger RtnCode;
@property (nonatomic, copy) NSString * _Nonnull RtnMsg;
@property (nonatomic, copy) NSString * _Nonnull Token;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





















@class WKUserContentController;
@class WKScriptMessage;

@interface WebViewController (SWIFT_EXTENSION(ECPayPaymentGatewayKit)) <WKScriptMessageHandler>
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end

@class WKWebViewConfiguration;
@class WKNavigationAction;
@class WKWindowFeatures;
@class WKFrameInfo;

@interface WebViewController (SWIFT_EXTENSION(ECPayPaymentGatewayKit)) <WKUIDelegate>
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
@end

@class WKNavigationResponse;

@interface WebViewController (SWIFT_EXTENSION(ECPayPaymentGatewayKit)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationResponse:(WKNavigationResponse * _Nonnull)navigationResponse decisionHandler:(void (^ _Nonnull)(WKNavigationResponsePolicy))decisionHandler;
@end

@class UIColor;
@class UINavigationController;

SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit14WebViewManager")
@interface WebViewManager : NSObject
+ (void)showWeb:(NSString * _Nonnull)url title:(NSString * _Nullable)title completion:(void (^ _Nullable)(void))completion;
+ (void)showWeb:(NSString * _Nonnull)url from:(UIViewController * _Nullable)from title:(NSString * _Nullable)title completion:(void (^ _Nullable)(void))completion;
+ (void)showWeb:(NSString * _Nonnull)url from:(UIViewController * _Nullable)from title:(NSString * _Nullable)title navColor:(UIColor * _Nullable)navColor completion:(void (^ _Nullable)(void))completion;
+ (UIViewController * _Nonnull)getWebViewControllerUseIntermediate:(NSString * _Nonnull)url title:(NSString * _Nullable)title completion:(void (^ _Nullable)(void))completion SWIFT_WARN_UNUSED_RESULT;
+ (UINavigationController * _Nonnull)getWebNavUseIntermediate:(NSString * _Nonnull)url parameters:(NSDictionary<NSString *, id> * _Nonnull)parameters title:(NSString * _Nullable)title customErrorMessageParam:(CustomErrorMessageParam * _Nullable)customErrorMessageParam completion:(void (^ _Nullable)(void))completion SWIFT_WARN_UNUSED_RESULT;
+ (UINavigationController * _Nonnull)getWebNavUseIntermediate:(NSString * _Nonnull)url parameters:(NSDictionary<NSString *, id> * _Nonnull)parameters title:(NSString * _Nullable)title customErrorMessageParam:(CustomErrorMessageParam * _Nullable)customErrorMessageParam exitConfirmParm:(ExitConfirmParm * _Nullable)exitConfirmParm completion:(void (^ _Nullable)(void))completion SWIFT_WARN_UNUSED_RESULT;
+ (void)showWebUseIntermediate:(NSString * _Nonnull)url title:(NSString * _Nullable)title completion:(void (^ _Nullable)(void))completion;
+ (void)showWebUseIntermediate:(NSString * _Nonnull)url from:(UIViewController * _Nullable)from title:(NSString * _Nullable)title completion:(void (^ _Nullable)(void))completion;
/// 載入原生瀏覽器
/// \param url 目標URL
///
+ (void)showNativeWeb:(NSString * _Nonnull)url completion:(void (^ _Nullable)(void))completion;
/// 載入原生瀏覽器，使用中轉頁
/// \param url 目標URL
///
+ (void)showNativeWebUseIntermediate:(NSString * _Nonnull)url completion:(void (^ _Nullable)(void))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22ECPayPaymentGatewayKit23XMLConfigurationManager")
@interface XMLConfigurationManager : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@class PublicKey;
@class EncryptedMessage;
@class PrivateKey;
enum DigestType : NSInteger;
@class Signature;
@class VerificationResult;

SWIFT_CLASS_NAMED("_objc_ClearMessage")
@interface ClearMessage : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull base64String;
@property (nonatomic, readonly, copy) NSData * _Nonnull data;
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithString:(NSString * _Nonnull)string using:(NSUInteger)rawEncoding error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)stringWithEncoding:(NSUInteger)rawEncoding error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (EncryptedMessage * _Nullable)encryptedWith:(PublicKey * _Nonnull)key padding:(SecPadding)padding error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (Signature * _Nullable)signedWith:(PrivateKey * _Nonnull)key digestType:(enum DigestType)digestType error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (VerificationResult * _Nullable)verifyWith:(PublicKey * _Nonnull)key signature:(Signature * _Nonnull)signature digestType:(enum DigestType)digestType error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("_objc_EncryptedMessage")
@interface EncryptedMessage : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull base64String;
@property (nonatomic, readonly, copy) NSData * _Nonnull data;
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (ClearMessage * _Nullable)decryptedWith:(PrivateKey * _Nonnull)key padding:(SecPadding)padding error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("_objc_PrivateKey")
@interface PrivateKey : NSObject
@property (nonatomic, readonly) SecKeyRef _Nonnull reference;
@property (nonatomic, readonly, copy) NSData * _Nullable originalData;
- (NSString * _Nullable)pemStringAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)dataAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)base64StringAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithData:(NSData * _Nonnull)data error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithReference:(SecKeyRef _Nonnull)reference error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithPemEncoded:(NSString * _Nonnull)pemString error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithPemNamed:(NSString * _Nonnull)pemName in:(NSBundle * _Nonnull)bundle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithDerNamed:(NSString * _Nonnull)derName in:(NSBundle * _Nonnull)bundle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("_objc_PublicKey")
@interface PublicKey : NSObject
@property (nonatomic, readonly) SecKeyRef _Nonnull reference;
@property (nonatomic, readonly, copy) NSData * _Nullable originalData;
- (NSString * _Nullable)pemStringAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)dataAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)base64StringAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithData:(NSData * _Nonnull)data error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithReference:(SecKeyRef _Nonnull)reference error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithPemEncoded:(NSString * _Nonnull)pemString error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithPemNamed:(NSString * _Nonnull)pemName in:(NSBundle * _Nonnull)bundle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithDerNamed:(NSString * _Nonnull)derName in:(NSBundle * _Nonnull)bundle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<PublicKey *> * _Nonnull)publicKeysWithPemEncoded:(NSString * _Nonnull)pemString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("_objc_Signature")
@interface Signature : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull base64String;
@property (nonatomic, readonly, copy) NSData * _Nonnull data;
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DigestType, open) {
  DigestTypeSha1 = 0,
  DigestTypeSha224 = 1,
  DigestTypeSha256 = 2,
  DigestTypeSha384 = 3,
  DigestTypeSha512 = 4,
};


SWIFT_CLASS_NAMED("_objc_VerificationResult")
@interface VerificationResult : NSObject
@property (nonatomic, readonly) BOOL isSuccessful;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
